export default [
  {"description": "Energia elétrica",      "amount": "150.55", "type": "saída", "frequency": "eventual", "date": "2022-01-10"},
  {"description": "Água",                  "amount": "75.55",  "type": "saída", "frequency": "recorrente", "date": "2022-01-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2022-01-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2022-01-23"},
  {"description": "Compras do mês",        "amount": "625.78", "type": "saída", "frequency": "recorrente", "date": "2022-01-23"},
  {"description": "Lanche",                "amount": "45.70",  "type": "saída", "frequency": "eventual",   "date": "2022-01-23"},
  {"description": "Blusa",                 "amount": "95.70",  "type": "saída", "frequency": "eventual",   "date": "2022-01-23"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2022-02-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "recorrente", "date": "2022-02-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2022-02-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-02-23"},
  {"description": "Compras do mês",        "amount": "540.00", "type": "saída", "frequency": "recorrente", "date": "2022-02-25"},
  {"description": "Parcela do Celular 1/5","amount": "150.99", "type": "saída", "frequency": "eventual",   "date": "2022-02-26"},
  {"description": "Cinema",                "amount": "45.00",  "type": "saída", "frequency": "eventual",   "date": "2022-02-23"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2022-03-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "recorrente", "date": "2022-03-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-03-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-03-23"},
  {"description": "Compras do mês",        "amount": "800.50", "type": "saída", "frequency": "recorrente", "date": "2022-03-17"},
  {"description": "Parcela do Celular 2/5","amount": "150.99", "type": "saída", "frequency": "eventual",   "date": "2022-03-18"},
  {"description": "Troca de Óleo do carro","amount": "90.00",  "type": "saída", "frequency": "eventual",   "date": "2022-03-23"},
  {"description": "Energia elétrica",      "amount": "75.99",  "type": "saída", "frequency": "recorrente", "date": "2022-04-10"},
  {"description": "Água",                  "amount": "80.33",  "type": "saída", "frequency": "recorrente", "date": "2022-04-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2022-04-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2022-04-23"},
  {"description": "Compras do mês",        "amount": "600.00", "type": "saída", "frequency": "recorrente", "date": "2022-04-25"},
  {"description": "Parcela do Celular 3/5","amount": "150.99", "type": "saída", "frequency": "eventual",   "date": "2022-04-26"},
  {"description": "Ebook de React Js",     "amount": "85.95",  "type": "saída", "frequency": "eventual",   "date": "2022-04-13"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2022-05-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "eventual", "date": "2022-05-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2022-05-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2022-05-23"},
  {"description": "Compras do mês",        "amount": "540.00", "type": "saída", "frequency": "recorrente", "date": "2022-05-25"},
  {"description": "Parcela do Celular 4/5","amount": "150.99", "type": "saída", "frequency": "eventual",   "date": "2022-05-26"},
  {"description": "Netflix",               "amount": "29.90",  "type": "saída", "frequency": "eventual",   "date": "2022-05-29"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2022-06-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "recorrente", "date": "2022-06-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-06-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-06-23"},
  {"description": "Compras do mês",        "amount": "700.00", "type": "saída", "frequency": "eventual", "date": "2022-06-20"},
  {"description": "Parcela do Celular 5/5","amount": "150.99", "type": "saída", "frequency": "eventual",   "date": "2022-06-26"},
  {"description": "Jantar no Restaurante",  "amount": "150.00", "type": "saída", "frequency": "eventual",   "date": "2022-06-28"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2022-07-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "eventual", "date": "2022-07-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-07-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-07-23"},
  {"description": "Compras do mês",        "amount": "560.00", "type": "saída", "frequency": "recorrente", "date": "2022-07-25"},
  {"description": "Assinatura do Jornal",   "amount": "19.90",  "type": "saída", "frequency": "eventual",   "date": "2022-07-28"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2022-08-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "eventual", "date": "2022-08-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-08-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-08-23"},
  {"description": "Compras do mês",        "amount": "680.00", "type": "saída", "frequency": "recorrente", "date": "2022-08-25"},
  {"description": "Manutenção do Carro",    "amount": "250.00", "type": "saída", "frequency": "eventual",   "date": "2022-08-30"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2022-09-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "eventual", "date": "2022-09-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-09-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-09-23"},
  {"description": "Compras do mês",        "amount": "520.00", "type": "saída", "frequency": "recorrente", "date": "2022-09-25"},
  {"description": "Almoço com Amigos",      "amount": "80.00",  "type": "saída", "frequency": "eventual",   "date": "2022-09-29"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2022-10-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "recorrente", "date": "2022-10-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-10-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-10-23"},
  {"description": "Compras do mês",        "amount": "600.00", "type": "saída", "frequency": "recorrente", "date": "2022-10-25"},
  {"description": "Parcela do Carro 1/48", "amount": "500.00", "type": "saída", "frequency": "eventual",   "date": "2022-10-26"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2022-11-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "recorrente", "date": "2022-11-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-11-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-11-23"},
  {"description": "Compras do mês",        "amount": "540.00", "type": "saída", "frequency": "recorrente", "date": "2022-11-25"},
  {"description": "Viagem",                "amount": "1500.00","type": "saída", "frequency": "eventual",   "date": "2022-11-30"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2022-12-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "eventual", "date": "2022-12-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2022-12-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2022-12-23"},
  {"description": "Compras do mês",        "amount": "800.00", "type": "saída", "frequency": "recorrente", "date": "2022-12-25"},
  {"description": "Presentes de Natal",    "amount": "200.00", "type": "saída", "frequency": "eventual",   "date": "2022-12-20"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2023-01-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "eventual", "date": "2023-01-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2023-01-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2023-01-23"},
  {"description": "Compras do mês",        "amount": "600.00", "type": "saída", "frequency": "recorrente", "date": "2023-01-25"},
  {"description": "Parcela do Carro 2/48", "amount": "500.00", "type": "saída", "frequency": "eventual",   "date": "2023-01-26"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "recorrente", "date": "2023-02-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "eventual", "date": "2023-02-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2023-02-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2023-02-23"},
  {"description": "Compras do mês",        "amount": "580.00", "type": "saída", "frequency": "recorrente", "date": "2023-02-25"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "eventual", "date": "2023-03-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "eventual", "date": "2023-03-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2023-03-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2023-03-23"},
  {"description": "Compras do mês",        "amount": "700.00", "type": "saída", "frequency": "recorrente", "date": "2023-03-25"},
  {"description": "Energia elétrica",      "amount": "97.00",  "type": "saída", "frequency": "eventual", "date": "2023-04-10"},
  {"description": "Água",                  "amount": "100.10", "type": "saída", "frequency": "eventual", "date": "2023-04-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "recorrente", "date": "2023-04-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2023-04-23"},
  {"description": "Compras do mês",        "amount": "500.00", "type": "saída", "frequency": "recorrente", "date": "2023-04-25"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2023-05-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "recorrente", "date": "2023-05-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2023-05-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2023-05-23"},
  {"description": "Compras do mês",        "amount": "500.00", "type": "saída", "frequency": "recorrente", "date": "2023-06-25"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "eventual", "date": "2023-06-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "recorrente", "date": "2023-06-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2023-06-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2023-06-23"},
  {"description": "Compras do mês",        "amount": "500.00", "type": "saída", "frequency": "eventual", "date": "2023-07-25"},
  {"description": "Energia elétrica",      "amount": "125.55", "type": "saída", "frequency": "recorrente", "date": "2023-07-10"},
  {"description": "Água",                  "amount": "90.15",  "type": "saída", "frequency": "recorrente", "date": "2023-07-15"},
  {"description": "Telefone",              "amount": "99.99",  "type": "saída", "frequency": "eventual", "date": "2023-07-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2023-07-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "recorrente", "date": "2023-08-23"},
  {"description": "Plano de Saúde",        "amount": "300.00", "type": "saída", "frequency": "eventual", "date": "2023-09-23"}
]